spring:
  datasource:
    url: jdbc:mysql://localhost:3306/printing_service?useUnicode=true&characterEncoding=utf-8&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    expose-request-attributes: true
    template-loader-path: classpath:/templates
    suffix: .ftl